/**
 * Created by paulex on 10/09/17.
 */


/**
 *
 * @param app
 * @param API {API}
 * @param jsonParser
 * @param urlencodedParser
 */
module.exports.controller = function (app, {API, jsonParser, urlencodedParser}) {
    app.use('/reports*', (req, res, next) => API.recognitions().auth(req, res, next));

    app.get('/reports/dashboard_basic', urlencodedParser, (req, res) => {
        // console.log(req.who)
        return API.reports().getBasicDashboard(req.who)
            .then(({data, code}) => res.status(code).send(data))
            .catch(({err, code}) => res.status(code).send(err));
    });

    /**
     * Disconnection Order
     * Description: This dashboard displays the number of Disconnection Orders (DO) generated
     **/
    app.get('/reports/disconnection_order', (req, res) => {
        return API.reports().getDisconnectionOrder(req.query)
            .then(({data, code}) => res.status(code).send(data))
            .catch(({err, code}) => res.status(code).send(err));
    });

    /**
     * Disconnection Order By Group
     * Description: This dashboard displays the number of Disconnection Orders (DO) generated by groups.
     **/
    app.get('/reports/disconnection_order/disconnection_order_by_group/:groupId', urlencodedParser, (req, res) => {
        return API.reports().getDisconnectionOrderByGroup(req.params['groupId'], req.query)
            .then(({data, code}) => {
                return res.status(code).send(data);
            })
            .catch(({err, code}) => {
                return res.status(code).send(err);
            });
    });

    /**
     * Disconnection Order By Business Unit
     * Description: This dashboard displays the number of Disconnection Orders (DO) generated by BU.
     **/
    app.get('/reports/disconnection_order/disconnection_order_by_bu/:groupId/:buId', urlencodedParser, (req, res) => {
        return API.reports().getDisconnectionOrderByBu(req.params['groupId'], req.params['buId'], req.query)
            .then(({data, code}) => {
                return res.status(code).send(data);
            })
            .catch(({err, code}) => {
                return res.status(code).send(err);
            });
    });

    /**
     * Disconnection Order By Undertaking
     * Description: This dashboard displays the number of Disconnection Orders (DO) generated by UT.
     **/
    app.get('/reports/disconnection_order/disconnection_order_by_ut/:groupId/:buId/:utId', urlencodedParser, (req, res) => {
        return API.reports().getDisconnectionOrderByUt(req.params['groupId'], req.params['buId'], req.params['utId'], req.query)
            .then(({data, code}) => {
                return res.status(code).send(data);
            })
            .catch(({err, code}) => {
                return res.status(code).send(err);
            });
    });

    /**
     * DC-RC Status Lookup
     * Description: This report displays current and historical statuses of a Disconnection Order or a Reconnection Order.
     **/
    app.get('/reports/dc_rc_status_lookup', urlencodedParser, (req, res) => {
        return API.reports().getStatusLookup(req.query)
            .then(({data, code}) => res.status(code).send(data))
            .catch(({err, code}) => res.status(code).send(err));
    });

    /**
     * DC RC Performance Indices
     * Description: This dashboard displays Performance indices (completions or pending) on disconnections and reconnections.
     **/
    app.get('/reports/dc_rc_performance_indices', urlencodedParser, (req, res) => {
        return API.reports().getPerformanceIndices(req.query)
            .then(({data, code}) => {
                return res.status(code).send(data);
            })
            .catch(({err, code}) => {
                return res.status(code).send(err);
            });
    });

    /**
     * DC RC Performance Indices By BU
     * Description: This dashboard displays Performance indices (completions or pending) on disconnections and reconnections by BU
     **/
    app.get('/reports/dc_rc_performance_indices/dc_rc_performance_indices_by_bu/:buId', urlencodedParser, (req, res) => {
        return API.reports().getPerformanceIndicesByBu(req.params['buId'], req.query)
            .then(({data, code}) => {
                return res.status(code).send(data);
            })
            .catch(({err, code}) => {
                return res.status(code).send(err);
            });
    });

    /**
     * DC RC Performance Indices By UT
     * Description: This dashboard displays Performance indices (completions or pending) on disconnections and reconnections by UT
     **/
    app.get('/reports/dc_rc_performance_indices/dc_rc_performance_indices_by_ut/:buId/:utId', urlencodedParser, (req, res) => {
        return API.reports().getPerformanceIndicesByUt(req.params['buId'], req.params['utId'], req.query)
            .then(({data, code}) => {
                return res.status(code).send(data);
            })
            .catch(({err, code}) => {
                return res.status(code).send(err);
            });
    });
};