
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries

    const data = [
        {short_code: "AL", name: "Albania", phone_code : 355},
        {short_code: "DZ", name: "Algeria", phone_code : 213},
        {short_code: "AS", name: "American Samoa", phone_code : 1684},
        {short_code: "AD", name: "Andorra", phone_code : 376},
        {short_code: "AO", name: "Angola", phone_code : 244},
        {short_code: "AI", name: "Anguilla", phone_code : 1264},
        {short_code: "AQ", name: "Antarctica", phone_code : 0},
        {short_code: "AG", name: "Antigua And Barbuda", phone_code : 1268},
        {short_code: "AR", name: "Argentina", phone_code : 54},
        {short_code: "AM", name: "Armenia", phone_code : 374},
        {short_code: "AW", name: "Aruba", phone_code : 297},
        {short_code: "AU", name: "Australia", phone_code : 61},
        {short_code: "AT", name: "Austria", phone_code : 43},
        {short_code: "AZ", name: "Azerbaijan", phone_code : 994},
        {short_code: "BS", name: "Bahamas The", phone_code : 1242},
        {short_code: "BH", name: "Bahrain", phone_code : 973},
        {short_code: "BD", name: "Bangladesh", phone_code : 880},
        {short_code: "BB", name: "Barbados", phone_code : 1246},
        {short_code: "BY", name: "Belarus", phone_code : 375},
        {short_code: "BE", name: "Belgium", phone_code : 32},
        {short_code: "BZ", name: "Belize", phone_code : 501},
        {short_code: "BJ", name: "Benin", phone_code : 229},
        {short_code: "BM", name: "Bermuda", phone_code : 1441},
        {short_code: "BT", name: "Bhutan", phone_code : 975},
        {short_code: "BO", name: "Bolivia", phone_code : 591},
        {short_code: "BA", name: "Bosnia and Herzegovina", phone_code : 387},
        {short_code: "BW", name: "Botswana", phone_code : 267},
        {short_code: "BV", name: "Bouvet Island", phone_code : 0},
        {short_code: "BR", name: "Brazil", phone_code : 55},
        {short_code: "IO", name: "British Indian Ocean Territory", phone_code : 246},
        {short_code: "BN", name: "Brunei", phone_code : 673},
        {short_code: "BG", name: "Bulgaria", phone_code : 359},
        {short_code: "BF", name: "Burkina Faso", phone_code : 226},
        {short_code: "BI", name: "Burundi", phone_code : 257},
        {short_code: "KH", name: "Cambodia", phone_code : 855},
        {short_code: "CM", name: "Cameroon", phone_code : 237},
        {short_code: "CA", name: "Canada", phone_code : 1},
        {short_code: "CV", name: "Cape Verde", phone_code : 238},
        {short_code: "KY", name: "Cayman Islands", phone_code : 1345},
        {short_code: "CF", name: "Central African Republic", phone_code : 236},
        {short_code: "TD", name: "Chad", phone_code : 235},
        {short_code: "CL", name: "Chile", phone_code : 56},
        {short_code: "CN", name: "China", phone_code : 86},
        {short_code: "CX", name: "Christmas Island", phone_code : 61},
        {short_code: "CC", name: "Cocos (Keeling) Islands", phone_code : 672},
        {short_code: "CO", name: "Colombia", phone_code : 57},
        {short_code: "KM", name: "Comoros", phone_code : 269},
        {short_code: "CG", name: "Congo", phone_code : 242},
        {short_code: "CD", name: "Congo The Democratic Republic Of The", phone_code : 242},
        {short_code: "CK", name: "Cook Islands", phone_code : 682},
        {short_code: "CR", name: "Costa Rica", phone_code : 506},
        {short_code: "CI", name: "Cote D'Ivoire (Ivory Coast)", phone_code : 225},
        {short_code: "HR", name: "Croatia (Hrvatska)", phone_code : 385},
        {short_code: "CU", name: "Cuba", phone_code : 53},
        {short_code: "CY", name: "Cyprus", phone_code : 357},
        {short_code: "CZ", name: "Czech Republic", phone_code : 420},
        {short_code: "DK", name: "Denmark", phone_code : 45},
        {short_code: "DJ", name: "Djibouti", phone_code : 253},
        {short_code: "DM", name: "Dominica", phone_code : 1767},
        {short_code: "DO", name: "Dominican Republic", phone_code : 1809},
        {short_code: "TP", name: "East Timor", phone_code : 670},
        {short_code: "EC", name: "Ecuador", phone_code : 593},
        {short_code: "EG", name: "Egypt", phone_code : 20},
        {short_code: "SV", name: "El Salvador", phone_code : 503},
        {short_code: "GQ", name: "Equatorial Guinea", phone_code : 240},
        {short_code: "ER", name: "Eritrea", phone_code : 291},
        {short_code: "EE", name: "Estonia", phone_code : 372},
        {short_code: "ET", name: "Ethiopia", phone_code : 251},
        {short_code: "XA", name: "External Territories of Australia", phone_code : 61},
        {short_code: "FK", name: "Falkland Islands", phone_code : 500},
        {short_code: "FO", name: "Faroe Islands", phone_code : 298},
        {short_code: "FJ", name: "Fiji Islands", phone_code : 679},
        {short_code: "FI", name: "Finland", phone_code : 358},
        {short_code: "FR", name: "France", phone_code : 33},
        {short_code: "GF", name: "French Guiana", phone_code : 594},
        {short_code: "PF", name: "French Polynesia", phone_code : 689},
        {short_code: "TF", name: "French Southern Territories", phone_code : 0},
        {short_code: "GA", name: "Gabon", phone_code : 241},
        {short_code: "GM", name: "Gambia The", phone_code : 220},
        {short_code: "GE", name: "Georgia", phone_code : 995},
        {short_code: "DE", name: "Germany", phone_code : 49},
        {short_code: "GH", name: "Ghana", phone_code : 233},
        {short_code: "GI", name: "Gibraltar", phone_code : 350},
        {short_code: "GR", name: "Greece", phone_code : 30},
        {short_code: "GL", name: "Greenland", phone_code : 299},
        {short_code: "GD", name: "Grenada", phone_code : 1473},
        {short_code: "GP", name: "Guadeloupe", phone_code : 590},
        {short_code: "GU", name: "Guam", phone_code : 1671},
        {short_code: "GT", name: "Guatemala", phone_code : 502},
        {short_code: "XU", name: "Guernsey and Alderney", phone_code : 44},
        {short_code: "GN", name: "Guinea", phone_code : 224},
        {short_code: "GW", name: "Guinea-Bissau", phone_code : 245},
        {short_code: "GY", name: "Guyana", phone_code : 592},
        {short_code: "HT", name: "Haiti", phone_code : 509},
        {short_code: "HM", name: "Heard and McDonald Islands", phone_code : 0},
        {short_code: "HN", name: "Honduras", phone_code : 504},
        {short_code: "HK", name: "Hong Kong S.A.R.", phone_code : 852},
        {short_code: "HU", name: "Hungary", phone_code : 36},
        {short_code: "IS", name: "Iceland", phone_code : 354},
        {short_code: "IN", name: "India", phone_code : 91},
        {short_code: "ID", name: "Indonesia", phone_code : 62},
        {short_code: "IR", name: "Iran", phone_code : 98},
        {short_code: "IQ", name: "Iraq", phone_code : 964},
        {short_code: "IE", name: "Ireland", phone_code : 353},
        {short_code: "IL", name: "Israel", phone_code : 972},
        {short_code: "IT", name: "Italy", phone_code : 39},
        {short_code: "JM", name: "Jamaica", phone_code : 1876},
        {short_code: "JP", name: "Japan", phone_code : 81},
        {short_code: "XJ", name: "Jersey", phone_code : 44},
        {short_code: "JO", name: "Jordan", phone_code : 962},
        {short_code: "KZ", name: "Kazakhstan", phone_code : 7},
        {short_code: "KE", name: "Kenya", phone_code : 254},
        {short_code: "KI", name: "Kiribati", phone_code : 686},
        {short_code: "KP", name: "Korea North", phone_code : 850},
        {short_code: "KR", name: "Korea South", phone_code : 82},
        {short_code: "KW", name: "Kuwait", phone_code : 965},
        {short_code: "KG", name: "Kyrgyzstan", phone_code : 996},
        {short_code: "LA", name: "Laos", phone_code : 856},
        {short_code: "LV", name: "Latvia", phone_code : 371},
        {short_code: "LB", name: "Lebanon", phone_code : 961},
        {short_code: "LS", name: "Lesotho", phone_code : 266},
        {short_code: "LR", name: "Liberia", phone_code : 231},
        {short_code: "LY", name: "Libya", phone_code : 218},
        {short_code: "LI", name: "Liechtenstein", phone_code : 423},
        {short_code: "LT", name: "Lithuania", phone_code : 370},
        {short_code: "LU", name: "Luxembourg", phone_code : 352},
        {short_code: "MO", name: "Macau S.A.R.", phone_code : 853},
        {short_code: "MK", name: "Macedonia", phone_code : 389},
        {short_code: "MG", name: "Madagascar", phone_code : 261},
        {short_code: "MW", name: "Malawi", phone_code : 265},
        {short_code: "MY", name: "Malaysia", phone_code : 60},
        {short_code: "MV", name: "Maldives", phone_code : 960},
        {short_code: "ML", name: "Mali", phone_code : 223},
        {short_code: "MT", name: "Malta", phone_code : 356},
        {short_code: "XM", name: "Man (Isle of)", phone_code : 44},
        {short_code: "MH", name: "Marshall Islands", phone_code : 692},
        {short_code: "MQ", name: "Martinique", phone_code : 596},
        {short_code: "MR", name: "Mauritania", phone_code : 222},
        {short_code: "MU", name: "Mauritius", phone_code : 230},
        {short_code: "YT", name: "Mayotte", phone_code : 269},
        {short_code: "MX", name: "Mexico", phone_code : 52},
        {short_code: "FM", name: "Micronesia", phone_code : 691},
        {short_code: "MD", name: "Moldova", phone_code : 373},
        {short_code: "MC", name: "Monaco", phone_code : 377},
        {short_code: "MN", name: "Mongolia", phone_code : 976},
        {short_code: "MS", name: "Montserrat", phone_code : 1664},
        {short_code: "MA", name: "Morocco", phone_code : 212},
        {short_code: "MZ", name: "Mozambique", phone_code : 258},
        {short_code: "MM", name: "Myanmar", phone_code : 95},
        {short_code: "NA", name: "Namibia", phone_code : 264},
        {short_code: "NR", name: "Nauru", phone_code : 674},
        {short_code: "NP", name: "Nepal", phone_code : 977},
        {short_code: "AN", name: "Netherlands Antilles", phone_code : 599},
        {short_code: "NL", name: "Netherlands The", phone_code : 31},
        {short_code: "NC", name: "New Caledonia", phone_code : 687},
        {short_code: "NZ", name: "New Zealand", phone_code : 64},
        {short_code: "NI", name: "Nicaragua", phone_code : 505},
        {short_code: "NE", name: "Niger", phone_code : 227},
        {short_code: "NG", name: "Nigeria", phone_code : 234},
        {short_code: "NU", name: "Niue", phone_code : 683},
        {short_code: "NF", name: "Norfolk Island", phone_code : 672},
        {short_code: "MP", name: "Northern Mariana Islands", phone_code : 1670},
        {short_code: "NO", name: "Norway", phone_code : 47},
        {short_code: "OM", name: "Oman", phone_code : 968},
        {short_code: "PK", name: "Pakistan", phone_code : 92},
        {short_code: "PW", name: "Palau", phone_code : 680},
        {short_code: "PS", name: "Palestinian Territory Occupied", phone_code : 970},
        {short_code: "PA", name: "Panama", phone_code : 507},
        {short_code: "PG", name: "Papua new Guinea", phone_code : 675},
        {short_code: "PY", name: "Paraguay", phone_code : 595},
        {short_code: "PE", name: "Peru", phone_code : 51},
        {short_code: "PH", name: "Philippines", phone_code : 63},
        {short_code: "PN", name: "Pitcairn Island", phone_code : 0},
        {short_code: "PL", name: "Poland", phone_code : 48},
        {short_code: "PT", name: "Portugal", phone_code : 351},
        {short_code: "PR", name: "Puerto Rico", phone_code : 1787},
        {short_code: "QA", name: "Qatar", phone_code : 974},
        {short_code: "RE", name: "Reunion", phone_code : 262},
        {short_code: "RO", name: "Romania", phone_code : 40},
        {short_code: "RU", name: "Russia", phone_code : 70},
        {short_code: "RW", name: "Rwanda", phone_code : 250},
        {short_code: "SH", name: "Saint Helena", phone_code : 290},
        {short_code: "KN", name: "Saint Kitts And Nevis", phone_code : 1869},
        {short_code: "LC", name: "Saint Lucia", phone_code : 1758},
        {short_code: "PM", name: "Saint Pierre and Miquelon", phone_code : 508},
        {short_code: "VC", name: "Saint Vincent And The Grenadines", phone_code : 1784},
        {short_code: "WS", name: "Samoa", phone_code : 684},
        {short_code: "SM", name: "San Marino", phone_code : 378},
        {short_code: "ST", name: "Sao Tome and Principe", phone_code : 239},
        {short_code: "SA", name: "Saudi Arabia", phone_code : 966},
        {short_code: "SN", name: "Senegal", phone_code : 221},
        {short_code: "RS", name: "Serbia", phone_code : 381},
        {short_code: "SC", name: "Seychelles", phone_code : 248},
        {short_code: "SL", name: "Sierra Leone", phone_code : 232},
        {short_code: "SG", name: "Singapore", phone_code : 65},
        {short_code: "SK", name: "Slovakia", phone_code : 421},
        {short_code: "SI", name: "Slovenia", phone_code : 386},
        {short_code: "XG", name: "Smaller Territories of the UK", phone_code : 44},
        {short_code: "SB", name: "Solomon Islands", phone_code : 677},
        {short_code: "SO", name: "Somalia", phone_code : 252},
        {short_code: "ZA", name: "South Africa", phone_code : 27},
        {short_code: "GS", name: "South Georgia", phone_code : 0},
        {short_code: "SS", name: "South Sudan", phone_code : 211},
        {short_code: "ES", name: "Spain", phone_code : 34},
        {short_code: "LK", name: "Sri Lanka", phone_code : 94},
        {short_code: "SD", name: "Sudan", phone_code : 249},
        {short_code: "SR", name: "Suriname", phone_code : 597},
        {short_code: "SJ", name: "Svalbard And Jan Mayen Islands", phone_code : 47},
        {short_code: "SZ", name: "Swaziland", phone_code : 268},
        {short_code: "SE", name: "Sweden", phone_code : 46},
        {short_code: "CH", name: "Switzerland", phone_code : 41},
        {short_code: "SY", name: "Syria", phone_code : 963},
        {short_code: "TW", name: "Taiwan", phone_code : 886},
        {short_code: "TJ", name: "Tajikistan", phone_code : 992},
        {short_code: "TZ", name: "Tanzania", phone_code : 255},
        {short_code: "TH", name: "Thailand", phone_code : 66},
        {short_code: "TG", name: "Togo", phone_code : 228},
        {short_code: "TK", name: "Tokelau", phone_code : 690},
        {short_code: "TO", name: "Tonga", phone_code : 676},
        {short_code: "TT", name: "Trinidad And Tobago", phone_code : 1868},
        {short_code: "TN", name: "Tunisia", phone_code : 216},
        {short_code: "TR", name: "Turkey", phone_code : 90},
        {short_code: "TM", name: "Turkmenistan", phone_code : 7370},
        {short_code: "TC", name: "Turks And Caicos Islands", phone_code : 1649},
        {short_code: "TV", name: "Tuvalu", phone_code : 688},
        {short_code: "UG", name: "Uganda", phone_code : 256},
        {short_code: "UA", name: "Ukraine", phone_code : 380},
        {short_code: "AE", name: "United Arab Emirates", phone_code : 971},
        {short_code: "GB", name: "United Kingdom", phone_code : 44},
        {short_code: "US", name: "United States", phone_code : 1},
        {short_code: "UM", name: "United States Minor Outlying Islands", phone_code : 1},
        {short_code: "UY", name: "Uruguay", phone_code : 598},
        {short_code: "UZ", name: "Uzbekistan", phone_code : 998},
        {short_code: "VU", name: "Vanuatu", phone_code : 678},
        {short_code: "VA", name: "Vatican City State (Holy See)", phone_code : 39},
        {short_code: "VE", name: "Venezuela", phone_code : 58},
        {short_code: "VN", name: "Vietnam", phone_code : 84},
        {short_code: "VG", name: "Virgin Islands (British)", phone_code : 1284},
        {short_code: "VI", name: "Virgin Islands (US)", phone_code : 1340},
        {short_code: "WF", name: "Wallis And Futuna Islands", phone_code : 681},
        {short_code: "EH", name: "Western Sahara", phone_code : 212},
        {short_code: "YE", name: "Yemen", phone_code : 967},
        {short_code: "YU", name: "Yugoslavia", phone_code : 38},
        {short_code: "ZM", name: "Zambia", phone_code : 260},
        {short_code: "ZW", name: "Zimbabwe", phone_code : 263}
    ];


    return knex('countries').del()
    .then(function () {
      // Inserts seed entries
      return knex('countries').insert(data);
    });
};
