
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries

    const data = [
        {name: "Andhra Pradesh", country_id: 101},
        {name: "Arunachal Pradesh", country_id: 101},
        {name: "Assam", country_id: 101},
        {name: "Bihar", country_id: 101},
        {name: "Chandigarh", country_id: 101},
        {name: "Chhattisgarh", country_id: 101},
        {name: "Dadra and Nagar Haveli", country_id: 101},
        {name: "Daman and Diu", country_id: 101},
        {name: "Delhi", country_id: 101},
        {name: "Goa", country_id: 101},
        {name: "Gujarat", country_id: 101},
        {name: "Haryana", country_id: 101},
        {name: "Himachal Pradesh", country_id: 101},
        {name: "Jammu and Kashmir", country_id: 101},
        {name: "Jharkhand", country_id: 101},
        {name: "Karnataka", country_id: 101},
        {name: "Kenmore", country_id: 101},
        {name: "Kerala", country_id: 101},
        {name: "Lakshadweep", country_id: 101},
        {name: "Madhya Pradesh", country_id: 101},
        {name: "Maharashtra", country_id: 101},
        {name: "Manipur", country_id: 101},
        {name: "Meghalaya", country_id: 101},
        {name: "Mizoram", country_id: 101},
        {name: "Nagaland", country_id: 101},
        {name: "Narora", country_id: 101},
        {name: "Natwar", country_id: 101},
        {name: "Odisha", country_id: 101},
        {name: "Paschim Medinipur", country_id: 101},
        {name: "Pondicherry", country_id: 101},
        {name: "Punjab", country_id: 101},
        {name: "Rajasthan", country_id: 101},
        {name: "Sikkim", country_id: 101},
        {name: "Tamil Nadu", country_id: 101},
        {name: "Telangana", country_id: 101},
        {name: "Tripura", country_id: 101},
        {name: "Uttar Pradesh", country_id: 101},
        {name: "Uttarakhand", country_id: 101},
        {name: "Vaishali", country_id: 101},
        {name: "West Bengal", country_id: 101},
        {name: "Badakhshan", country_id: 1},
        {name: "Badgis", country_id: 1},
        {name: "Baglan", country_id: 1},
        {name: "Balkh", country_id: 1},
        {name: "Bamiyan", country_id: 1},
        {name: "Farah", country_id: 1},
        {name: "Faryab", country_id: 1},
        {name: "Gawr", country_id: 1},
        {name: "Gazni", country_id: 1},
        {name: "Herat", country_id: 1},
        {name: "Hilmand", country_id: 1},
        {name: "Jawzjan", country_id: 1},
        {name: "Kabul", country_id: 1},
        {name: "Kapisa", country_id: 1},
        {name: "Khawst", country_id: 1},
        {name: "Kunar", country_id: 1},
        {name: "Lagman", country_id: 1},
        {name: "Lawghar", country_id: 1},
        {name: "Nangarhar", country_id: 1},
        {name: "Nimruz", country_id: 1},
        {name: "Nuristan", country_id: 1},
        {name: "Paktika", country_id: 1},
        {name: "Paktiya", country_id: 1},
        {name: "Parwan", country_id: 1},
        {name: "Qandahar", country_id: 1},
        {name: "Qunduz", country_id: 1},
        {name: "Samangan", country_id: 1},
        {name: "Sar-e Pul", country_id: 1},
        {name: "Takhar", country_id: 1},
        {name: "Uruzgan", country_id: 1},
        {name: "Wardag", country_id: 1},
        {name: "Zabul", country_id: 1},
        {name: "Berat", country_id: 2},
        {name: "Bulqize", country_id: 2},
        {name: "Delvine", country_id: 2},
        {name: "Devoll", country_id: 2},
        {name: "Dibre", country_id: 2},
        {name: "Durres", country_id: 2},
        {name: "Elbasan", country_id: 2},
        {name: "Fier", country_id: 2},
        {name: "Gjirokaster", country_id: 2},
        {name: "Gramsh", country_id: 2},
        {name: "Has", country_id: 2},
        {name: "Kavaje", country_id: 2},
        {name: "Kolonje", country_id: 2},
        {name: "Korce", country_id: 2},
        {name: "Kruje", country_id: 2},
        {name: "Kucove", country_id: 2},
        {name: "Kukes", country_id: 2},
        {name: "Kurbin", country_id: 2},
        {name: "Lezhe", country_id: 2},
        {name: "Librazhd", country_id: 2},
        {name: "Lushnje", country_id: 2},
        {name: "Mallakaster", country_id: 2},
        {name: "Malsi e Madhe", country_id: 2},
        {name: "Mat", country_id: 2},
        {name: "Mirdite", country_id: 2},
        {name: "Peqin", country_id: 2},
        {name: "Permet", country_id: 2},
        {name: "Pogradec", country_id: 2},
        {name: "Puke", country_id: 2},
        {name: "Sarande", country_id: 2},
        {name: "Shkoder", country_id: 2},
        {name: "Skrapar", country_id: 2},
        {name: "Tepelene", country_id: 2},
        {name: "Tirane", country_id: 2},
        {name: "Tropoje", country_id: 2},
        {name: "Vlore", country_id: 2},
        {name: "'Ayn Daflah", country_id: 3},
        {name: "'Ayn Tamushanat", country_id: 3},
        {name: "Adrar", country_id: 3},
        {name: "Algiers", country_id: 3},
        {name: "Annabah", country_id: 3},
        {name: "Bashshar", country_id: 3},
        {name: "Batnah", country_id: 3},
        {name: "Bijayah", country_id: 3},
        {name: "Biskrah", country_id: 3},
        {name: "Blidah", country_id: 3},
        {name: "Buirah", country_id: 3},
        {name: "Bumardas", country_id: 3},
        {name: "Burj Bu Arririj", country_id: 3},
        {name: "Ghalizan", country_id: 3},
        {name: "Ghardayah", country_id: 3},
        {name: "Ilizi", country_id: 3},
        {name: "Jijili", country_id: 3},
        {name: "Jilfah", country_id: 3},
        {name: "Khanshalah", country_id: 3},
        {name: "Masilah", country_id: 3},
        {name: "Midyah", country_id: 3},
        {name: "Milah", country_id: 3},
        {name: "Muaskar", country_id: 3},
        {name: "Mustaghanam", country_id: 3},
        {name: "Naama", country_id: 3},
        {name: "Oran", country_id: 3},
        {name: "Ouargla", country_id: 3},
        {name: "Qalmah", country_id: 3},
        {name: "Qustantinah", country_id: 3},
        {name: "Sakikdah", country_id: 3},
        {name: "Satif", country_id: 3},
        {name: "Sayda'", country_id: 3},
        {name: "Sidi ban-al-'Abbas", country_id: 3},
        {name: "Suq Ahras", country_id: 3},
        {name: "Tamanghasat", country_id: 3},
        {name: "Tibazah", country_id: 3},
        {name: "Tibissah", country_id: 3},
        {name: "Tilimsan", country_id: 3},
        {name: "Tinduf", country_id: 3},
        {name: "Tisamsilt", country_id: 3},
        {name: "Tiyarat", country_id: 3},
        {name: "Tizi Wazu", country_id: 3},
        {name: "Umm-al-Bawaghi", country_id: 3},
        {name: "Wahran", country_id: 3},
        {name: "Warqla", country_id: 3},
        {name: "Wilaya d Alger", country_id: 3},
        {name: "Wilaya de Bejaia", country_id: 3},
        {name: "Wilaya de Constantine", country_id: 3},
        {name: "al-Aghwat", country_id: 3},
        {name: "al-Bayadh", country_id: 3},
        {name: "al-Jaza'ir", country_id: 3},
        {name: "al-Wad", country_id: 3},
        {name: "ash-Shalif", country_id: 3},
        {name: "at-Tarif", country_id: 3},
        {name: "Eastern", country_id: 4},
        {name: "Manu'a", country_id: 4},
        {name: "Swains Island", country_id: 4},
        {name: "Western", country_id: 4},
        {name: "Andorra la Vella", country_id: 5},
        {name: "Canillo", country_id: 5},
        {name: "Encamp", country_id: 5},
        {name: "La Massana", country_id: 5},
        {name: "Les Escaldes", country_id: 5},
        {name: "Ordino", country_id: 5},
        {name: "Sant Julia de Loria", country_id: 5},
        {name: "Bengo", country_id: 6},
        {name: "Benguela", country_id: 6},
        {name: "Bie", country_id: 6},
        {name: "Cabinda", country_id: 6},
        {name: "Cunene", country_id: 6},
        {name: "Huambo", country_id: 6},
        {name: "Huila", country_id: 6},
        {name: "Kuando-Kubango", country_id: 6},
        {name: "Kwanza Norte", country_id: 6},
        {name: "Kwanza Sul", country_id: 6},
        {name: "Luanda", country_id: 6},
        {name: "Lunda Norte", country_id: 6},
        {name: "Lunda Sul", country_id: 6},
        {name: "Malanje", country_id: 6},
        {name: "Moxico", country_id: 6},
        {name: "Namibe", country_id: 6},
        {name: "Uige", country_id: 6},
        {name: "Zaire", country_id: 6},
        {name: "Other Provinces", country_id: 7},
        {name: "Sector claimed by Argentina/Ch", country_id: 8},
        {name: "Sector claimed by Argentina/UK", country_id: 8},
        {name: "Sector claimed by Australia", country_id: 8},
        {name: "Sector claimed by France", country_id: 8},
        {name: "Sector claimed by New Zealand", country_id: 8},
        {name: "Sector claimed by Norway", country_id: 8},
        {name: "Unclaimed Sector", country_id: 8},
        {name: "Barbuda", country_id: 9},
        {name: "Saint George", country_id: 9},
        {name: "Saint John", country_id: 9},
        {name: "Saint Mary", country_id: 9},
        {name: "Saint Paul", country_id: 9},
        {name: "Saint Peter", country_id: 9},
        {name: "Saint Philip", country_id: 9},
        {name: "Buenos Aires", country_id: 10},
        {name: "Catamarca", country_id: 10},
        {name: "Chaco", country_id: 10},
        {name: "Chubut", country_id: 10},
        {name: "Cordoba", country_id: 10},
        {name: "Corrientes", country_id: 10},
        {name: "Distrito Federal", country_id: 10},
        {name: "Entre Rios", country_id: 10},
        {name: "Formosa", country_id: 10},
        {name: "Jujuy", country_id: 10},
        {name: "La Pampa", country_id: 10},
        {name: "La Rioja", country_id: 10},
        {name: "Mendoza", country_id: 10},
        {name: "Misiones", country_id: 10},
        {name: "Neuquen", country_id: 10},
        {name: "Rio Negro", country_id: 10},
        {name: "Salta", country_id: 10},
        {name: "San Juan", country_id: 10},
        {name: "San Luis", country_id: 10},
        {name: "Santa Cruz", country_id: 10},
        {name: "Santa Fe", country_id: 10},
        {name: "Santiago del Estero", country_id: 10},
        {name: "Tierra del Fuego", country_id: 10},
        {name: "Tucuman", country_id: 10},
        {name: "Aragatsotn", country_id: 11},
        {name: "Ararat", country_id: 11},
        {name: "Armavir", country_id: 11},
        {name: "Gegharkunik", country_id: 11},
        {name: "Kotaik", country_id: 11},
        {name: "Lori", country_id: 11},
        {name: "Shirak", country_id: 11},
        {name: "Stepanakert", country_id: 11},
        {name: "Syunik", country_id: 11},
        {name: "Tavush", country_id: 11},
        {name: "Vayots Dzor", country_id: 11},
        {name: "Yerevan", country_id: 11},
        {name: "Aruba", country_id: 12},
        {name: "Auckland", country_id: 13},
        {name: "Australian Capital Territory", country_id: 13},
        {name: "Balgowlah", country_id: 13},
        {name: "Balmain", country_id: 13},
        {name: "Bankstown", country_id: 13},
        {name: "Baulkham Hills", country_id: 13},
        {name: "Bonnet Bay", country_id: 13},
        {name: "Camberwell", country_id: 13},
        {name: "Carole Park", country_id: 13},
        {name: "Castle Hill", country_id: 13},
        {name: "Caulfield", country_id: 13},
        {name: "Chatswood", country_id: 13},
        {name: "Cheltenham", country_id: 13},
        {name: "Cherrybrook", country_id: 13},
        {name: "Clayton", country_id: 13},
        {name: "Collingwood", country_id: 13},
        {name: "Frenchs Forest", country_id: 13},
        {name: "Hawthorn", country_id: 13},
        {name: "Jannnali", country_id: 13},
        {name: "Knoxfield", country_id: 13},
        {name: "Melbourne", country_id: 13},
        {name: "New South Wales", country_id: 13},
        {name: "Northern Territory", country_id: 13},
        {name: "Perth", country_id: 13},
        {name: "Queensland", country_id: 13},
        {name: "South Australia", country_id: 13},
        {name: "Tasmania", country_id: 13},
        {name: "Templestowe", country_id: 13},
        {name: "Victoria", country_id: 13},
        {name: "Werribee south", country_id: 13},
        {name: "Western Australia", country_id: 13},
        {name: "Wheeler", country_id: 13},
        {name: "Bundesland Salzburg", country_id: 14},
        {name: "Bundesland Steiermark", country_id: 14},
        {name: "Bundesland Tirol", country_id: 14},
        {name: "Burgenland", country_id: 14},
        {name: "Carinthia", country_id: 14},
        {name: "Karnten", country_id: 14},
        {name: "Liezen", country_id: 14},
        {name: "Lower Austria", country_id: 14},
        {name: "Niederosterreich", country_id: 14},
        {name: "Oberosterreich", country_id: 14},
        {name: "Salzburg", country_id: 14},
        {name: "Schleswig-Holstein", country_id: 14},
        {name: "Steiermark", country_id: 14},
        {name: "Styria", country_id: 14},
        {name: "Tirol", country_id: 14},
        {name: "Upper Austria", country_id: 14},
        {name: "Vorarlberg", country_id: 14},
        {name: "Wien", country_id: 14},
        {name: "Abseron", country_id: 15},
        {name: "Baki Sahari", country_id: 15},
        {name: "Ganca", country_id: 15},
        {name: "Ganja", country_id: 15},
        {name: "Kalbacar", country_id: 15},
        {name: "Lankaran", country_id: 15},
        {name: "Mil-Qarabax", country_id: 15},
        {name: "Mugan-Salyan", country_id: 15},
        {name: "Nagorni-Qarabax", country_id: 15},
        {name: "Naxcivan", country_id: 15},
        {name: "Priaraks", country_id: 15},
        {name: "Qazax", country_id: 15},
        {name: "Saki", country_id: 15},
        {name: "Sirvan", country_id: 15},
        {name: "Xacmaz", country_id: 15},
        {name: "Abaco", country_id: 16},
        {name: "Acklins Island", country_id: 16},
        {name: "Andros", country_id: 16},
        {name: "Berry Islands", country_id: 16},
        {name: "Biminis", country_id: 16},
        {name: "Cat Island", country_id: 16},
        {name: "Crooked Island", country_id: 16},
        {name: "Eleuthera", country_id: 16},
        {name: "Exuma and Cays", country_id: 16},
        {name: "Grand Bahama", country_id: 16},
        {name: "Inagua Islands", country_id: 16},
        {name: "Long Island", country_id: 16},
        {name: "Mayaguana", country_id: 16},
        {name: "New Providence", country_id: 16},
        {name: "Ragged Island", country_id: 16},
        {name: "Rum Cay", country_id: 16},
        {name: "San Salvador", country_id: 16},
        {name: "'Isa", country_id: 17},
        {name: "Badiyah", country_id: 17},
        {name: "Hidd", country_id: 17},
        {name: "Jidd Hafs", country_id: 17},
        {name: "Mahama", country_id: 17},
        {name: "Manama", country_id: 17},
        {name: "Sitrah", country_id: 17},
        {name: "al-Manamah", country_id: 17},
        {name: "al-Muharraq", country_id: 17},
        {name: "ar-Rifa'a", country_id: 17},
        {name: "Bagar Hat", country_id: 18},
        {name: "Bandarban", country_id: 18},
        {name: "Barguna", country_id: 18},
        {name: "Barisal", country_id: 18},
        {name: "Bhola", country_id: 18},
        {name: "Bogora", country_id: 18},
        {name: "Brahman Bariya", country_id: 18},
        {name: "Chandpur", country_id: 18},
        {name: "Chattagam", country_id: 18},
        {name: "Chittagong Division", country_id: 18},
        {name: "Chuadanga", country_id: 18},
        {name: "Dhaka", country_id: 18},
        {name: "Dinajpur", country_id: 18},
        {name: "Faridpur", country_id: 18},
        {name: "Feni", country_id: 18},
        {name: "Gaybanda", country_id: 18},
        {name: "Gazipur", country_id: 18},
        {name: "Gopalganj", country_id: 18},
        {name: "Habiganj", country_id: 18},
        {name: "Jaipur Hat", country_id: 18},
        {name: "Jamalpur", country_id: 18},
        {name: "Jessor", country_id: 18},
        {name: "Jhalakati", country_id: 18},
        {name: "Jhanaydah", country_id: 18},
        {name: "Khagrachhari", country_id: 18},
        {name: "Khulna", country_id: 18},
        {name: "Kishorganj", country_id: 18},
        {name: "Koks Bazar", country_id: 18},
        {name: "Komilla", country_id: 18},
        {name: "Kurigram", country_id: 18},
        {name: "Kushtiya", country_id: 18},
        {name: "Lakshmipur", country_id: 18},
        {name: "Lalmanir Hat", country_id: 18},
        {name: "Madaripur", country_id: 18},
        {name: "Magura", country_id: 18},
        {name: "Maimansingh", country_id: 18},
        {name: "Manikganj", country_id: 18},
        {name: "Maulvi Bazar", country_id: 18},
        {name: "Meherpur", country_id: 18},
        {name: "Munshiganj", country_id: 18},
        {name: "Naral", country_id: 18},
        {name: "Narayanganj", country_id: 18},
        {name: "Narsingdi", country_id: 18},
        {name: "Nator", country_id: 18},
        {name: "Naugaon", country_id: 18},
        {name: "Nawabganj", country_id: 18},
        {name: "Netrakona", country_id: 18},
        {name: "Nilphamari", country_id: 18},
        {name: "Noakhali", country_id: 18},
        {name: "Pabna", country_id: 18},
        {name: "Panchagarh", country_id: 18},
        {name: "Patuakhali", country_id: 18},
        {name: "Pirojpur", country_id: 18},
        {name: "Rajbari", country_id: 18},
        {name: "Rajshahi", country_id: 18},
        {name: "Rangamati", country_id: 18},
        {name: "Rangpur", country_id: 18},
        {name: "Satkhira", country_id: 18},
        {name: "Shariatpur", country_id: 18},
        {name: "Sherpur", country_id: 18},
        {name: "Silhat", country_id: 18},
        {name: "Sirajganj", country_id: 18},
        {name: "Sunamganj", country_id: 18},
        {name: "Tangayal", country_id: 18},
        {name: "Thakurgaon", country_id: 18},
        {name: "Christ Church", country_id: 19},
        {name: "Saint Andrew", country_id: 19},
        {name: "Saint George", country_id: 19},
        {name: "Saint James", country_id: 19},
        {name: "Saint John", country_id: 19},
        {name: "Saint Joseph", country_id: 19},
        {name: "Saint Lucy", country_id: 19},
        {name: "Saint Michael", country_id: 19},
        {name: "Saint Peter", country_id: 19},
        {name: "Saint Philip", country_id: 19},
        {name: "Saint Thomas", country_id: 19},
        {name: "Brest", country_id: 20},
        {name: "Homjel'", country_id: 20},
        {name: "Hrodna", country_id: 20},
        {name: "Mahiljow", country_id: 20},
        {name: "Mahilyowskaya Voblasts", country_id: 20},
        {name: "Minsk", country_id: 20},
        {name: "Minskaja Voblasts'", country_id: 20},
        {name: "Petrik", country_id: 20},
        {name: "Vicebsk", country_id: 20},
        {name: "Antwerpen", country_id: 21},
        {name: "Berchem", country_id: 21},
        {name: "Brabant", country_id: 21},
        {name: "Brabant Wallon", country_id: 21},
        {name: "Brussel", country_id: 21},
        {name: "East Flanders", country_id: 21},
        {name: "Hainaut", country_id: 21},
        {name: "Liege", country_id: 21},
        {name: "Limburg", country_id: 21},
        {name: "Luxembourg", country_id: 21},
        {name: "Namur", country_id: 21},
        {name: "Ontario", country_id: 21},
        {name: "Oost-Vlaanderen", country_id: 21},
        {name: "Provincie Brabant", country_id: 21},
        {name: "Vlaams-Brabant", country_id: 21},
        {name: "Wallonne", country_id: 21},
        {name: "West-Vlaanderen", country_id: 21},
        {name: "Belize", country_id: 22},
        {name: "Cayo", country_id: 22},
        {name: "Corozal", country_id: 22},
        {name: "Orange Walk", country_id: 22},
        {name: "Stann Creek", country_id: 22},
        {name: "Toledo", country_id: 22},
        {name: "Alibori", country_id: 23},
        {name: "Atacora", country_id: 23},
        {name: "Atlantique", country_id: 23},
        {name: "Borgou", country_id: 23},
        {name: "Collines", country_id: 23},
        {name: "Couffo", country_id: 23},
        {name: "Donga", country_id: 23},
        {name: "Littoral", country_id: 23},
        {name: "Mono", country_id: 23},
        {name: "Oueme", country_id: 23},
        {name: "Plateau", country_id: 23},
        {name: "Zou", country_id: 23},
        {name: "Hamilton", country_id: 24},
        {name: "Saint George", country_id: 24},
        {name: "Bumthang", country_id: 25},
        {name: "Chhukha", country_id: 25},
        {name: "Chirang", country_id: 25},
        {name: "Daga", country_id: 25},
        {name: "Geylegphug", country_id: 25},
        {name: "Ha", country_id: 25},
        {name: "Lhuntshi", country_id: 25},
        {name: "Mongar", country_id: 25},
        {name: "Pemagatsel", country_id: 25},
        {name: "Punakha", country_id: 25},
        {name: "Rinpung", country_id: 25},
        {name: "Samchi", country_id: 25},
        {name: "Samdrup Jongkhar", country_id: 25},
        {name: "Shemgang", country_id: 25},
        {name: "Tashigang", country_id: 25},
        {name: "Timphu", country_id: 25},
        {name: "Tongsa", country_id: 25},
        {name: "Wangdiphodrang", country_id: 25},
        {name: "Beni", country_id: 26},
        {name: "Chuquisaca", country_id: 26},
        {name: "Cochabamba", country_id: 26},
        {name: "La Paz", country_id: 26},
        {name: "Oruro", country_id: 26},
        {name: "Pando", country_id: 26},
        {name: "Potosi", country_id: 26},
        {name: "Santa Cruz", country_id: 26},
        {name: "Tarija", country_id: 26},
        {name: "Federacija Bosna i Hercegovina", country_id: 27},
        {name: "Republika Srpska", country_id: 27},
        {name: "Central Bobonong", country_id: 28},
        {name: "Central Boteti", country_id: 28},
        {name: "Central Mahalapye", country_id: 28},
        {name: "Central Serowe-Palapye", country_id: 28},
        {name: "Central Tutume", country_id: 28},
        {name: "Chobe", country_id: 28},
        {name: "Francistown", country_id: 28},
        {name: "Gaborone", country_id: 28},
        {name: "Ghanzi", country_id: 28},
        {name: "Jwaneng", country_id: 28},
        {name: "Kgalagadi North", country_id: 28},
        {name: "Kgalagadi South", country_id: 28},
        {name: "Kgatleng", country_id: 28},
        {name: "Lagos", country_id: 28}
    ];

  return knex('states').del()
    .then(function () {
      // Inserts seed entries
      return knex('states').insert(data);
    });
};
